/** Pour rendre cliquables les tags AniList d'une fiche. */
const ANILIST_TO_CATALOG_GENRE = {
  Action: "Action",
  Adventure: "Aventure",
  Comedy: "Comédie",
  Drama: "Drame",
  Ecchi: "Ecchi",
  Fantasy: "Fantasy",
  Horror: "Horreur",
  "Mahou Shoujo": "Magical girl",
  Mecha: "Mechas",
  Music: "Musique",
  Mystery: "Mystère",
  Psychological: "Psychologique",
  Romance: "Romance",
  "Sci-Fi": "Science-fiction",
  "Slice of Life": "Slice of Life",
  Sports: "Sport",
  Supernatural: "Surnaturel",
  Thriller: "Thriller",
};

export function browseGenreFor(anilistGenre) {
  return ANILIST_TO_CATALOG_GENRE[anilistGenre] || null;
}

/** Figés ici : panneau de filtres sans requête. */
export const CATALOG_GENRES = [
  "Action",
  "Aventure",
  "Comédie",
  "Drame",
  "Romance",
  "Fantasy",
  "Science-fiction",
  "Horreur",
  "Sport",
  "Surnaturel",
  "Isekai",
  "Shônen",
  "Seinen",
  "Slice of Life",
  "Mystère",
  "Psychologique",
  "Adolescence",
  "Aliens / Extra-terrestres",
  "Amitié",
  "Amour",
  "Apocalypse",
  "Art",
  "Arts martiaux",
  "Assassinat",
  "Autre monde",
  "Combats",
  "Crime",
  "Cyberpunk",
  "Danse",
  "Démons",
  "Détective",
  "Donghua",
  "Dragon",
  "Ecchi",
  "Ecole",
  "Elfe",
  "Enquête",
  "Famille",
  "Fantastique",
  "Fantômes",
  "Futur",
  "Gastronomie",
  "Ghibli",
  "Guerre",
  "Harcèlement",
  "Harem",
  "Harem inversé",
  "Histoire",
  "Historique",
  "Homosexualité",
  "Jeunesse",
  "Jeux",
  "Jeux vidéo",
  "Josei",
  "Journalisme",
  "Kaï",
  "LGBT+",
  "Mafia",
  "Magical girl",
  "Magie",
  "Maladie",
  "Mariage",
  "Mature",
  "Mechas",
  "Médiéval",
  "Militaire",
  "Monde virtuel",
  "Monstres",
  "Musique",
  "Nekketsu",
  "Ninjas",
  "Nostalgie",
  "Paranormal",
  "Philosophie",
  "Pirates",
  "Police",
  "Politique",
  "Post-apocalyptique",
  "Pouvoirs psychiques",
  "Préhistoire",
  "Prison",
  "Quotidien",
  "Religion",
  "Réincarnation / Transmigration",
  "Samouraïs",
  "School Life",
  "Science-Fantasy",
  "Scientifique",
  "Shôjo",
  "Shôjo-Ai",
  "Shônen-Ai",
  "Société",
  "Super pouvoirs",
  "Super-héros",
  "Survie",
  "Survival game",
  "Technologies",
  "Thriller",
  "Tournois",
  "Travail",
  "Vampires",
  "Vengeance",
  "Voyage",
  "Voyage temporel",
  "Webcomic",
  "Yakuza",
  "Yaoi",
  "Yokai",
  "Yuri",
];
